MotenKonferens/MotenKonferens/Controllers/SiteLayoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Mvc;


namespace MK.Controllers
{
    public class SiteLayoutController : SurfaceController
    {
        private const string PARTIAL_VIEW_FOLDER = "~/Views/Partials/SiteLayout/";
        public ActionResult RenderHero()
        {
            return PartialView(PARTIAL_VIEW_FOLDER + "_Hero.cshtml");
        }
    }
}

MotenKonferens/MotenKonferens/Controllers/TemaLayoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Mvc;


namespace MK.Controllers
{
    public class TemaLayoutController : SurfaceController
    {
        private const string PARTIAL_VIEW_FOLDER = "~/Views/Partials/SiteLayout/";
        public ActionResult RenderImageArchive()
        {
            return PartialView(PARTIAL_VIEW_FOLDER + "_ImageArchive.cshtml");
        }
    }
}

MotenKonferens/MotenKonferens/Views/MacroPartials/BigImage.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage

@*
    Macro to display a gallery of images from the Media section.
    Works with either a 'Single Media Picker' or a 'Multiple Media Picker' macro parameter (see below).

    How it works:
        - Confirm the macro parameter has been passed in with a value
        - Loop through all the media Ids passed in (might be a single item, might be many)
        - Display any individual images, as well as any folders of images

    Macro Parameters To Create, for this macro to work:
    Alias:mediaIds     Name:Select folders and/or images    Type: Multiple Media Picker
                                                            Type: (note: You can use a Single Media Picker if that's more appropriate to your needs)
*@

@{ var mediaIds = Model.MacroParameters["mediaIds"] as string; }

@if (mediaIds != null)
{
    <div class="row">
        @foreach (var mediaId in mediaIds.Split(','))
        {
            var media = Umbraco.TypedMedia(mediaId);

            @* a single image *@
            if (media.DocumentTypeAlias == "Image")
            {
                @Render(media as Image);
            }

            @* a folder with images under it *@
            foreach (var image in media.Children<Image>())
            {
                @Render(image);
            }
        }
    </div>
}

@helper Render(Image item)
{
    <div class="column">
        <a href="@item.Url" class="thumbnail">
            <img src="@item.GetCropUrl(width:1200, height:600)" alt="@item.Name" />
        </a>
    </div>
}

MotenKonferens/MotenKonferens/Views/MacroPartials/ImageArchive.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage


@*
    Macro to display a series of images from a media folder.

    How it works:
        - Confirm the macro parameter has been passed in with a value
        - Loop through all the media Ids passed in (might be a single item, might be many)
        - Display any individual images, as well as any folders of images

    Macro Parameters To Create, for this macro to work:
    Alias:mediaId     Name:Select folder with images    Type:Single Media Picker
*@


@{ var mediaIds = Model.MacroParameters["mediaIds"] as string; }

@if (mediaIds != null)
{
    <div class="row">
        @foreach (var mediaId in mediaIds.Split(','))
        {
            var media = Umbraco.TypedMedia(mediaId);

            @* a single image *@
            if (media.DocumentTypeAlias == "Image")
            {
                @Render(media as Image);
            }

            @* a folder with images under it *@
            foreach (var image in media.Children<Image>())
            {
                @Render(image);
            }
        }
    </div>
}

MotenKonferens/MotenKonferens/Views/MacroPartials/InsertUmbracoFormWithTheme.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
	
@if (Model.MacroParameters["FormGuid"] != null)
{
    var s = Model.MacroParameters["FormGuid"].ToString();
    var theme = "";
    var includeScripts = true;

    @*
        If a theme is provided as a macro parameter, forms will attempt to use custom theme files
        ex: given the value "test", forms will look up views for the form and fields in a custom directory:

        Form will be rendered with
            /Views/Partials/Forms/Themes/test/form.cshml

        Fields will be rendered with
            /Views/Partials/Forms/Themes/test/FieldType/[fieldtypename].cshtml

        If a file is not available in the custom directory, forms will fallback to the default files in
            /Views/Partials/Forms/Themes/default/
    *@

    if(Model.MacroParameters.ContainsKey("FormTheme"))
    {
        theme = Model.MacroParameters["FormTheme"].ToString();
    }

    if (Model.MacroParameters.ContainsKey("ExcludeScripts"))
    {

        @*
            Inverse the boolean - RenderAction Parameter expects it to be false for exclusion
            But with default value for Macro Paramater boolean/checkbox being false 
            We want to ensure by default we include the scripts next to the form
        *@
        includeScripts = Model.MacroParameters["ExcludeScripts"].ToString() == "0";
    }

    var form = new Guid(s);
    var recordGuid = Guid.Empty;

    if (string.IsNullOrEmpty(Request.QueryString["recordId"]) == false)
    {
        Guid.TryParse(Request.QueryString["recordId"], out recordGuid);
    }

    Html.RenderAction("RenderForm", "UmbracoForms", new {formId = form, recordId = recordGuid, theme = theme, includeScripts = includeScripts });
}

MotenKonferens/MotenKonferens/Views/MacroPartials/ListSubPages.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage

@using Umbraco.Core.Models
@using Umbraco.Web

@*
    This snippet creates links for every single page (no matter how deep) below
    the page currently being viewed by the website visitor, displayed as nested unordered HTML lists.
*@

@{ var selection = Model.Content.Children.Where(x => x.IsVisible()).ToArray(); }

@* Ensure that the Current Page has children *@
@if (selection.Length > 0)
{
    @* Get the first page in the children, where the property umbracoNaviHide is not True *@
    var naviLevel = selection[0].Level;

    @* Add in level for a CSS hook *@
    <ul class="level-@(naviLevel)">
        @* Loop through the selection *@
        @foreach (var item in selection)
        {
            <li>
                <a href="@item.Url">@item.Name</a>

                @* if this child page has any children, where the property umbracoNaviHide is not True *@
                @{
                    var children = item.Children.Where(x => x.IsVisible()).ToArray();
                    if (children.Length > 0)
                    {
                        @* Call our helper to display the children *@
                        @ChildPages(children)
                    }
                }
            </li>
        }
    </ul>
}


@helper ChildPages(IPublishedContent[] selection)
{
    @* Ensure that we have a collection of pages *@
    if (selection.Length > 0)
    {
    @* Get the first page in pages and get the level *@
        var naviLevel = selection[0].Level;

    @* Add in level for a CSS hook *@
        <ul class="level-@(naviLevel)">
            @foreach (var item in selection)
            {
                <li>
                    <a href="@item.Url">@item.Name</a>

                    @* if the page has any children, where the property umbracoNaviHide is not True *@
                    @{
                        var children = item.Children.Where(x => x.IsVisible()).ToArray();
                        if (children.Length > 0)
                        {
                        @* Recurse and call our helper to display the children *@
                            @ChildPages(children)
                        }
                    }
                </li>
            }
        </ul>
    }
}

MotenKonferens/MotenKonferens/Views/MacroPartials/PageList.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@using Umbraco.Web


@*
    Macro to list all child pages under a specific page in the content tree.

    How it works:
        - Confirm the startNodeId macro parameter has been passed in with a value
        - Loop through all child pages
        - Display a list of link to those pages, sorted by the value of the propertyAlias

    Macro Parameters To Create, for this macro to work:
    Alias:startNodeId     Name:Select starting page    Type:Content Picker
*@

@{ var startNodeId = Model.MacroParameters["startNodeId"]; }

@if (startNodeId != null)
{
    @* Get the starting page *@
    var startNode = Umbraco.TypedContent(startNodeId);
    var selection = startNode.Children.Where(x => x.IsVisible()).ToArray();

    if (selection.Length > 0)
    {
        <ul>
            @foreach (var item in selection)
            {
                <li><a href="@item.Url">@item.Name</a></li>
            }
        </ul>
    }
}

MotenKonferens/MotenKonferens/Views/MacroPartials/PageListCompany.cshtml
@using ContentModels = Umbraco.Web.PublishedContentModels;
@using Umbraco.Web;
@inherits Umbraco.Web.Macros.PartialViewMacroPage

@{ 
    var startNodeId = Model.MacroParameters["startNodeId"] != null ? Model.MacroParameters["startNodeId"] : Model.Content.Id;
    var numberOfPosts = 4;
    if (Model.MacroParameters["numberOfPosts"] != null)
    {
        int.TryParse((string)Model.MacroParameters["numberOfPosts"], out numberOfPosts);
    }
}
@if (startNodeId != null)
{
    @* Get the starting page *@
    var startNode = Umbraco.TypedContent(startNodeId);
    var teman = startNode.Children.OrderByDescending(x => x.CreateDate).Take(numberOfPosts);

    if (teman.Any())
    {
    <div class=" margin-bottom anlaggning">
        <div class="columns">

            @foreach (ContentModels.Tema item in teman)
            {
                 string imageUrl = item.HasValue("HeaderImage") ? item.GetPropertyValue<IPublishedContent>("HeaderImage").Url : "";
                    string title = item.HasValue("title") ? item.GetPropertyValue<string>("title") : item.Name;
                    string description = item.GetPropertyValue<string>("PuffIngress");
                   
                    var color = Umbraco.GetPreValueAsString(item.GetPropertyValue<int>("PuffColor"));
                  //var bgcolor=int.Parse(Umbraco.GetPreValueAsString(item.GetPropertyValue<int>("PuffColor")));

                    <div class="column is-3 has-text-centered">
                         <div class="lightgrey">
                            <figure class="has-text-centered ">   
                                <h3 class="is-size-4-mobile"><a href="@item.Url">@item.PuffHeader</a></h3>
                                 <a href="@item.Url" class="thin">@item.PuffSubHeader</a>
                                 <a href="@item.Url"><img class="img-responsive" src="@(imageUrl)?width=282&height=120&mode=crop&anchor=center"></a>
                                 <div class="padding20 infotext">
                                    <p class="infobox">@description</p>
                                    <a href="@item.Url" class="button is-outlined ">Läs mer</a>
                                </div>  
                            </figure>
                        </div>
                         
                    </div>
            }
        </div>
    </div>
    }
}
 

MotenKonferens/MotenKonferens/Views/MacroPartials/PageListTema.cshtml
@using ContentModels = Umbraco.Web.PublishedContentModels;
@using Umbraco.Web;
@inherits Umbraco.Web.Macros.PartialViewMacroPage

@{ 
    var startNodeId = Model.MacroParameters["startNodeId"] != null ? Model.MacroParameters["startNodeId"] : Model.Content.Id;
    var numberOfPosts = 4;
    if (Model.MacroParameters["numberOfPosts"] != null)
    {
        int.TryParse((string)Model.MacroParameters["numberOfPosts"], out numberOfPosts);
    }
}
@if (startNodeId != null)
{
    @* Get the starting page *@
    var startNode = Umbraco.TypedContent(startNodeId);
    var teman = startNode.Children.OrderByDescending(x => x.CreateDate).Take(numberOfPosts);

    if (teman.Any())
    {
    <div class="tema margin-bottom">
        <div class="columns is-multiline">

            @foreach (ContentModels.Tema item in teman)
            {
                 string imageUrl = item.HasValue("HeaderImage") ? item.GetPropertyValue<IPublishedContent>("HeaderImage").Url : "";
                    string title = item.HasValue("title") ? item.GetPropertyValue<string>("title") : item.Name;
                    string description = item.GetPropertyValue<string>("PuffIngress");
                   
                    var color = Umbraco.GetPreValueAsString(item.GetPropertyValue<int>("PuffColor"));
                  //var bgcolor=int.Parse(Umbraco.GetPreValueAsString(item.GetPropertyValue<int>("PuffColor")));

                    <div class="column is-3 has-text-centered">
                         <div class="@color">
                            <figure class="has-text-centered ">   
                                <h3 class="is-size-4-mobile"><a href="@item.Url">@title</a></h3>
                                 <a href="@item.Url"><img class="img-responsive" src="@(imageUrl)?width=282&height=120&mode=crop&anchor=center"></a>
                                 <div class="padding20 infotext">
                                    <p class="infobox">@description</p>
                                    <a href="@item.Url" class="button is-outlined ">Läs mer</a>
                                </div>  
                            </figure>
                        </div>
                         
                    </div>
            }
        </div>
    </div>
    }
}
 

MotenKonferens/MotenKonferens/Views/MacroPartials/RenderUmbracoFormScripts.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@using Umbraco.Forms.Web.Controllers
@{
    var formsToRender = new List<Guid>();
    object forms = TempData["UmbracoForms"];
    if (forms != null)
    {
        formsToRender = (List<Guid>)forms;
    }

    // Reading TempData["UmbracoForms"] should have set it to null but this doesn't
    // happen if this request didn't return a 200 OK status. https://stackoverflow.com/a/7630709/5018
    // Explictly clear it so that on the next request the scripts don't get rendered.
    TempData.Remove("UmbracoForms");
}

@foreach (Guid form in formsToRender)
{
    Html.RenderAction("Render", "UmbracoForms", new { formId = form, mode = "script" });
}

MotenKonferens/MotenKonferens/Views/MacroPartials/Temapuffar.cshtml
@using ContentModels = Umbraco.Web.PublishedContentModels;
@using Umbraco.Web;
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@*<section class="section">
    <div class="container">
        <div class="tema margin-bottom">
            <div class="columns">
                   @foreach (ContentModels.Tema tema in Model.Content.Children)
                    {
                    var color = Umbraco.GetPreValueAsString(tema.PuffColor);
                    string imageUrl = tema.HasValue("PuffImage") ? (tema.PuffImage.Url) : "";
                    <div class="column is-3 has-text-centered has-text-white">
                         <div class="@color">
                            <figure class="has-text-centered ">   
                                <h3 class="is-size-4-mobile"><a href="@tema.Url">@tema.PageTitle</a></h3>
                                 <a href="@tema.Url"><img class="img-responsive" src="@(imageUrl)?width=282&height=120&mode=crop&anchor=center"></a>
                                 <div class="padding20 infotext">
                                    <p class="infobox">@tema.PuffIngress</p>
                                    <a href="@tema.Url" class="button is-outlined ">Läs mer</a>
                                </div>
                            </figure>
                        </div>
                    </div>
                } 
            </div>
        </div>
    </div>
</section>*@

MotenKonferens/MotenKonferens/Views/Master.cshtml
@using ContentModels = Umbraco.Web.PublishedContentModels;
@using Umbraco.Core
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = null;

    // Get basic design settings from the homepage
   ContentModels.Home home = Model.Content.Site() as ContentModels.Home;
     @*var colorTheme = Umbraco.GetPreValueAsString(home.ColorTheme);
    var font = Umbraco.GetPreValueAsString(home.Font);*@
}

<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>@Model.Content.Name - @home.Sitename</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="~/css/styles.min.css" rel="stylesheet" />
    <link rel="stylesheet" href='@Url.Content("~/css/styles.min.css")' />
    @RenderSection("Header", required: false)

</head>

<body>

    <div id="menu" class="is-hidden-mobile">
        <nav class="navbar toprow container">
            <div class="navbar-brand">
                <header class="header">
                    <div class="logo">
                        @if (home.SiteLogo != null && !string.IsNullOrEmpty(home.SiteLogo.Url))
                        {
                        <div class="nav-link--home">
                            <a href="@home.Url"><img class="logo-image" src="@home.SiteLogo.Url" alt="@home.Sitename" width="193"></a>
                        </div>
                        }
                        else
                        {
                        <a class="nav-link nav-link--home nav-link--home__text logo-text" href="/">@home.Sitename</a>
                        }
                    </div>
                </header>
            </div>
            <div class="container level is-mobile">
                <div class="level-item is-hidden-mobile  is-7">
                    <img title="Moten-konferens - Enkla, aktiva möten" src="~/images/moten_konferens_svart.png" width="360" alt="Moten-konferens - Enkla, aktiva möten ">
                </div>
                <div class="level-item is-hidden-mobile schwrp is-5">
                    <i class="fa fa-search" aria-hidden="true"></i>
                    <form action="/search/" method="GET">
                        <div id="search">
                            <input type="text" placeholder="Sök här..." name="query">
                            <button>SÖK</button>
                        </div>
                    </form>
                </div>
            </div>
        </nav>
    </div>
    <div class="container nav is-hidden-mobile">
        <nav id="navigation" class="navbar navigation navigation-landscape is-hidden-mobile">
            <div class="navbar-end ">
                <div class="menu-container container">
                    <div class="main-menu">
                        @Html.Partial("~/Views/Partials/Navigation/TopNavigation.cshtml")
                    </div>
                </div>
            </div>
        </nav>
    </div>
    <nav class="navbar is-hidden-desktop">
        <div class="navbar-brand">  <div class="navbar-item"><img id="__mcenew" src="/media/1055/logogkg.png?width=238&amp;height=37" alt="" width="200" height="25" data-udi="umb://media/293d8935aa664f5e869cc906de979020"></div></div>
    </nav>
    <div class="mmenu">
        <nav class="navbar  is-blue is-hidden-desktop" role="navigation" aria-label="main navigation">
            <div class="navbar-brand">
                <a class="navbar-item" href="/">
                    <img title="Moten-konferens - Enkla, aktiva möten" src="/media/1050/moten_konferens_vit.png" width="200" alt="Moten-konferens - Enkla, aktiva möten ">
                </a>

                <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false">
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                </a>

            </div>
        </nav>

        <div class="mobile-menu  is-hidden-desktop" id="navMenu">
            @Html.Partial("~/views/partials/navigation/topNavigation.cshtml")
        </div>
    </div>

    <main>
        @{Html.RenderAction("RenderHero", "SiteLayout");}  
        <div class="section">
            <div class="container">
                @RenderBody()
            </div>
        </div>
    </main>

    <footer class="footer ">
        <div class="container">
            <div class="sep">
                @Html.GetGridHtml(Model.Content.GetProperty("footerGrid", recurse: true), "Bootstrap3")
            </div>
        </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.1.0.min.js" integrity="sha256-cCueBR6CsyA4/9szpPfrX3s49M9vUU5BgtiJj06wt/s=" crossorigin="anonymous"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.13.1/jquery.validate.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/mvc/5.2.3/jquery.validate.unobtrusive.min.js"></script>
    <script src=" ~/scripts/umbraco-starterkit-app.js"></script>
    <script>
        $(document).on('scroll', function () {
            if ($(this).scrollTop() > 10) {
                $('#navigation').addClass('sticky');
                $('.mmenu').addClass('sticky');
                $('#show-logo').show().css('display', 'inline-block');
            }
            else {
                $('#navigation').removeClass('sticky');
                $('.mmenu').removeClass('sticky');
                $('#show-logo').hide();
            }
        });

        $('.navbar-burger').click(function () {
            $(this).toggleClass('bclose');
            $('#navMenu').slideToggle('fast');
        });
    </script>
</body>
</html>

MotenKonferens/MotenKonferens/Views/Partials/Grid/Bootstrap2-Fluid.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@* 
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }   
        }else { 
            <div class="container-fluid">
                <div class="row-fluid clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="@("span" + s.grid) column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>   
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Umbraco.If(singleColumn, "<div class='container-fluid'>")
        <div class="row-fluid clearfix">
            @foreach ( var area in row.areas ) {
            <div class="@("span" + area.grid) column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Umbraco.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties())
            {
                var propertyValue = HttpUtility.HtmlAttributeEncode(property.Value.ToString());
                attrs.Add(property.Name + "=\"" + propertyValue + "\"");
            }

        JObject style = contentItem.styles;

        if (style != null) {
            var cssVals = new List<string>();
            foreach (JProperty property in style.Properties())
            {
                var propertyValue = property.Value.ToString();
                if (string.IsNullOrWhiteSpace(propertyValue) == false)
                {
                    cssVals.Add(property.Name + ":" + propertyValue + ";");
                }
            }

            if (cssVals.Any())
                attrs.Add("style='" + HttpUtility.HtmlAttributeEncode(string.Join(" ", cssVals)) + "'");
        }

        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

MotenKonferens/MotenKonferens/Views/Partials/Grid/Bootstrap2.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }   
        }else { 
            <div class="container">
                <div class="row clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="@("span" + s.grid) column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>   
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Umbraco.If(singleColumn, "<div class='container'>")
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="@("span" + area.grid) column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Umbraco.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties())
            {
                var propertyValue = HttpUtility.HtmlAttributeEncode(property.Value.ToString());
                attrs.Add(property.Name + "=\"" + propertyValue + "\"");
            }

        JObject style = contentItem.styles;

        if (style != null) {
            var cssVals = new List<string>();
            foreach (JProperty property in style.Properties())
            {
                var propertyValue = property.Value.ToString();
                if (string.IsNullOrWhiteSpace(propertyValue) == false)
                {
                    cssVals.Add(property.Name + ":" + propertyValue + ";");
                }
            }

            if (cssVals.Any())
                attrs.Add("style=\"" + HttpUtility.HtmlAttributeEncode(string.Join(" ", cssVals)) + "\"");
        }

        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

MotenKonferens/MotenKonferens/Views/Partials/Grid/Bootstrap3-Fluid.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@*
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;

    <div>
        @if (oneColumn)
        {
            foreach (var section in Model.sections)
            {
                <div class="grid-section">
                    @foreach (var row in section.rows)
                    {
                        @renderRow(row);
                    }
                </div>
            }
        }
        else
        {
            <div>
                @foreach (var s in Model.sections)
                {
                    <div class="columns">
                        <div class="is-@s.grid column has-text-centered">
                            @foreach (var row in s.rows)
                            {
                                @renderRow(row);
                            }
                        </div>
                    </div>
                }
            </div>
        }
    </div>
}

@helper renderRow(dynamic row)
    {
        <div @RenderElementAttributes(row)>
            <div class="columns">
                @foreach (var area in row.areas)
                {
                    <div class="is-@area.grid column has-text-centered">
                        <div @RenderElementAttributes(area)>
                            @foreach (var control in area.controls)
                            {
                                if (control != null && control.editor != null && control.editor.view != null)
                                {
                                    <text>@Html.Partial("grid/editors/base", (object)control)</text>
                                }
                            }
                        </div>
                    </div>}
            </div>
        </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if (cfg != null)
            foreach (JProperty property in cfg.Properties())
            {
                var propertyValue = HttpUtility.HtmlAttributeEncode(property.Value.ToString());
                attrs.Add(property.Name + "=\"" + propertyValue + "\"");
            }

        JObject style = contentItem.styles;

        if (style != null)
        {
            var cssVals = new List<string>();
            foreach (JProperty property in style.Properties())
            {
                var propertyValue = property.Value.ToString();
                if (string.IsNullOrWhiteSpace(propertyValue) == false)
                {
                    cssVals.Add(property.Name + ":" + propertyValue + ";");
                }
            }

            if (cssVals.Any())
                attrs.Add("style='" + HttpUtility.HtmlAttributeEncode(string.Join(" ", cssVals)) + "'");
        }

        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

MotenKonferens/MotenKonferens/Views/Partials/Grid/Editors/Embed.cshtml
@model dynamic
@using Umbraco.Web.Templates


<div class="video-wrapper">
	@Html.Raw(Model.value)
</div>

MotenKonferens/MotenKonferens/Views/Partials/Grid/Editors/Rte.cshtml
@model dynamic
@using Umbraco.Web.Templates

@Html.Raw(TemplateUtilities.ParseInternalLinks(Model.value.ToString()))

MotenKonferens/MotenKonferens/Views/Partials/SiteLayout/PageContent.cshtml
@model IEnumerable<string>
@Model.Ingress;